services:
  backend:
    build:
      context: .
      dockerfile: Dockerfiles/backend/Dockerfile
    container_name: django-backend
    command: gunicorn --bind 0.0.0.0:8000 mysite.wsgi:application
    volumes:
      - ./mysite:/app
    expose:
      - "8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/frontend/Dockerfile
    container_name: react-frontend
    command: npm run build
    volumes:
      - ./account-react:/app
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.config
      - ./account-react/build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

  Mysql:
  image: mysql:8.0
  container_name: home_manager-db
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: home_manager
    MYSQL_USER: user
    MYSQL_PASSWORD: password
  ports:
    - "3306:3306"
  volumes:
    - db_data:/var/lib/mysql
    - ./db_init:/docker-entrypoint-initdb.d
